#!/bin/bash 

# Script to clean up latex generated by IPython nbconvert

# e.g.,
# f="GenericGeomorphicHamiltonian"; jupyter-nbconvert --to latex "../"$f".ipynb"; mv "../"$f".tex" .; ./parse_latex.sh $f".tex" "Generic geomorphic Hamiltonian"; pdflatex $f".tex"

tex_file=$1

if [ "$2" == "" ]; then
        new_title="${tex_file%.*}"
else
	new_title="$2"
fi

tmp_file="tmp.tex"

echo "New title: '$new_title'"

rm -f $tmp_file
cp $tex_file $tmp_file

awk '
/\\title/ {
	print("\\title{'"$new_title"'}");
	getline;
	#print("\\input{latexdefs}")
}

/\\section/ {
	gsub("section","section*",$0)
}

/\\subsection/ {
	gsub("subsection","subsection*",$0)
}

/\\subsubsection/ {
	gsub("subsubsection","subsubsection*",$0)
}

/\\section\{Summary\}/ {
	gsub("section","section*",$0)
}


# Skip this markup, which screws up the main font for the rest of the docs.
/prompt{Out}/ {
	getline
}

# Insert command to ensure PDF has white background
/begin{document}/ {
	print("\\pagecolor{white}")
	print("\\author{Colin P. Stark}")
}

# Cut all the command cells, which are tcolorbox wrapped
 {
	if (index($0,"begin{tcolorbox}")>0) {
		#print($0)
		do {
			getline;
			#print($0)
		} while (index($0,"end{tcolorbox}")==0)
		getline;
	}
	print($0)
}

' $tmp_file 1> $tex_file
rm -f $tmp_file
