['TimeInvariant_sinbeta_ramp_eta1p5_ratio0p5_xiv90',  'OneRay_eta1plus']
['TimeInvariant_sinbeta_ramp_eta1p5_ratio0p5_xiv60',  'OneRay_eta1plus']
['TimeInvariant_sinbeta_ramp_eta1p5_ratio0p5_xiv30',  'OneRay_eta1plus']
['TimeInvariant_sinbeta_ramp_eta1p0_ratio0p5_xiv100', 'OneRay_eta1']
['TimeInvariant_sinbeta_ramp_eta0p5_ratio0p5_xiv100', 'OneRay_eta1minus']
['TimeInvariant_sinbeta_ramp_eta0p5_ratio0p5_xiv60',  'OneRay_eta1minus']
['TimeInvariant_sinbeta_ramp_eta0p5_ratio0p5_xiv30',  'OneRay_eta1minus']
